/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface": "#e5e2e1",
        "inverse-primary": "#735c00",
        "on-error-container": "#ffdad6",
        "on-primary-fixed": "#241a00",
        "on-error": "#690005",
        "surface": "#131313",
        "primary": "#f2ca50",
        "surface-container-highest": "#353535",
        "surface-bright": "#393939",
        "on-tertiary": "#2f3131",
        "on-secondary-fixed-variant": "#474747",
        "on-primary-fixed-variant": "#574500",
        "surface-container-lowest": "#0e0e0e",
        "error-container": "#93000a",
        "surface-dim": "#131313",
        "surface-container-high": "#2a2a2a",
        "tertiary-fixed": "#e2e2e2",
        "secondary": "#c8c6c6",
        "on-tertiary-container": "#444546",
        "on-surface-variant": "#d0c5af",
        "on-primary-container": "#554300",
        "on-background": "#e5e2e1",
        "surface-container": "#20201f",
        "surface-container-low": "#1c1b1b",
        "on-secondary-fixed": "#1b1c1c",
        "on-secondary-container": "#b6b5b4",
        "primary-fixed-dim": "#e9c349",
        "background": "#131313",
        "inverse-surface": "#e5e2e1",
        "inverse-on-surface": "#313030",
        "on-secondary": "#303030",
        "surface-tint": "#e9c349",
        "outline-variant": "#4d4635",
        "primary-fixed": "#ffe088",
        "on-tertiary-fixed": "#1a1c1c",
        "error": "#ffb4ab",
        "on-primary": "#3c2f00",
        "surface-variant": "#353535",
        "secondary-fixed-dim": "#c8c6c6",
        "secondary-fixed": "#e4e2e1",
        "on-tertiary-fixed-variant": "#454747",
        "tertiary-container": "#b2b3b3",
        "tertiary-fixed-dim": "#c6c6c7",
        "secondary-container": "#474747",
        "primary-container": "#d4af37",
        "outline": "#99907c",
        "tertiary": "#cecece"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
